---
title: "Peanuts for working"
date: 2025-01-26
categories: ["eccentricity"]
---

I eat peanuts for lunch every day and am often called upon to defend this practice. Although the reasons are, to me, completely obvious, I have not yet been able to convince any of my colleagues. Hopefully my reasoning will be more persuasive as a written argument.

## I eat other foods too

First let’s establish the scope of my claim. Just as it does not follow that teachers live at school simply because that is where you always see them, I do not eat peanuts for every meal—only for lunch. 

Peanuts have unique advantages that make them the optimal lunch food. I am specifically advocating for this use.

## Imagine the perfect lunch food? Were you picturing a peanut?

What do we desire from a lunch food? A lunch food should be easy to prepare, inexpensive, and nutritious. The peanut is not just the optimal combination of these properties, I will show that it is in fact the archetypal characterization of each and thus, without a doubt, the perfect lunch food.

### Preparation, what preparation?

Peanuts are always there for you when you need them. They don’t even need to be remembered. Simply storing a bag of peanuts at your desk or a container in your bag will ensure that you never forget your lunch or feel the chore of making it in advance. Then at work, there’s no need to wait for the microwave.

### P = MC

Peanuts are a global commodity. Not only are they a bountiful crop, making them naturally inexpensive to produce, they are also traded in a perfectly competitive market—you always know you’ll be able to buy your peanuts at a fair price.

### A real health nut

Peanuts are high in healthy fats and protein and are a good source of many micronutrients. It has even been shown that daily peanut consumption can reduce your risk of heart disease. They’re also completely natural.

### That’s not all

Peanuts can be eaten without any utensils reducing waste of single-use plastics, they will last months stored at room temperature and they’re extremely dense—a serving of peanuts will occupy less space than any other lunch food.

## Variety Schmariety

So with all these undeniable benefits, why are peanuts not eaten by everyone around the lunch table?  By far the most common critique is that I am ignoring the value of variety. Yes, screech the (anti-)peanut gallery, I would get bored eating the same thing every day. But this argument is unsound. Variety would be a reason not to eat only peanuts, yet it is proposed by those who do not eat any peanuts. Even a lover of variety could, no doubt, enjoy the benefits of the peanut once or twice a week without losing interest.

There is also a blatant double standard in the demand for variety. Observe that variety is only valued at lunch or dinner. For breakfast it is almost more common to eat the same cereal, porridge or toast every day. There is no fundamental reason why lunch should be any different.

If the peanut was not so remarkably superior to any other lunch food—say if its price were tripled or if I were mildly allergic—I might begin to entertain some other options. But in the current market the peanut wins every time. You would have to be nuts not to eat peanuts for lunch.

---

The views expressed in this paper are solely those of the author and may differ from official Bank of Canada views. No responsibility for them should be attributed to the Bank.

Slides are available upon request.
