project:
  type: website

execute:
  freeze: auto

website:
  title: "HStern"
  favicon: "/static/assets/favicon.ico"
  navbar:
    logo-href: "https://hstern.ca"
    left:
      - text: "Blog"
        href: "/blog/"
      - text: "Tools"
        href: "/tools/"
      - text: "Notes"
        href: "/notes/"
    background: "secondary"
    foreground: "primary"
  sidebar:
    - id: cfa_3
      title: "CFA Level III"
      collapse-level: 3
      style: floating
      border: false
      contents:
        - section: "Portfolio Management"
          contents: blog/notes/portfolio-management/**/*.qmd
    - id: resume #placeholder necessary for hybrid sidebar
      title: ""
      style: docked
      alignment: center
      background: primary
      foreground: secondary
      border: false
  page-navigation: true
  comments:
    giscus:
      repo: henrystern/hstern_blog
      repo-id: R_kgDOJphxWw
      category: Announcements
      category-id: DIC_kwDOJphxW84CW2Ug
      mapping: pathname
      reactions-enabled: false
      theme:
        light: light_high_contrast
        dark: dark_dimmed

format:
  html:
    pagetitle: "{{< meta title >}} | Henry Stern"
    title-block-banner: true
    toc: true
    toc-title: "\n"
    include-in-header:
      - ./static/html/header.html
    include-before-body:
      - ./static/html/before-body.html
    include-after-body:
      - ./static/html/after-body.html
    theme: 
      light:
        - flatly
        - ./static/css/custom-light.scss
      dark:
        - darkly
        - ./static/css/custom-dark.scss
    css: ./static/css/styles.css
