project:
  type: website

website:
  title: "HStern"
  navbar:
    left:
      - text: "Resume"
        href: "https://hstern.ca/resume/"
      - text: "Tools"
        href: "https://hstern.ca/tools/"
      - text: "Blog"
        href: "https://hstern.ca/blog/"
    background: "secondary"
    foreground: "primary"
  favicon: "/static/assets/favicon.ico"
format:
  html:
    include-in-header:
      - ./static/html/preload.html
    include-before-body:
      - ./static/html/highlight_active.html
    theme: 
      light:
        - flatly
        - ./static/css/custom-light.scss
      dark:
        - darkly
        - ./static/css/custom-dark.scss
    css: ./static/css/styles.css
    toc: true
