project:
  type: website

website:
  title: "HStern"
  favicon: "/static/assets/favicon.ico"
  navbar:
    logo-href: "https://hstern.ca"
    left:
      - text: "Resume"
        href: "https://hstern.ca/resume/"
      - text: "Tools"
        href: "https://hstern.ca/tools/"
      - text: "Blog"
        href: "https://hstern.ca/blog/"
    background: "secondary"
    foreground: "primary"
  comments:
    giscus:
      repo: henrystern/hstern_blog
      repo-id: R_kgDOJphxWw
      category: Announcements
      category-id: DIC_kwDOJphxW84CW2Ug
      mapping: pathname
      reactions-enabled: false
      theme:
        light: light_high_contrast
        dark: dark_dimmed

format:
  html:
    include-in-header:
      - ./static/html/header.html
    include-before-body:
      - ./static/html/before-body.html
    include-after-body:
      - ./static/html/after-body.html
    theme: 
      light:
        - flatly
        - ./static/css/custom-light.scss
      dark:
        - darkly
        - ./static/css/custom-dark.scss
    css: ./static/css/styles.css
    toc: true
    toc-title: Contents
